# Generated by Django 6.0.3 on 2026-03-08 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField()),
                ('input_url', models.URLField(blank=True, null=True)),
                ('trust_score', models.IntegerField(default=0)),
                ('verdict', models.CharField(choices=[('REAL', 'Real'), ('LIKELY_REAL', 'Likely Real'), ('UNCERTAIN', 'Uncertain'), ('LIKELY_FAKE', 'Likely Fake'), ('FAKE', 'Fake')], max_length=20)),
                ('reasoning', models.TextField(blank=True)),
                ('source_analysis', models.TextField(blank=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analysis_history',
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
