# Generated by Django 5.2.1 on 2026-05-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysishistory',
            name='gemini_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='analysishistory',
            name='input_mode',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='analysishistory',
            name='key_claims',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='analysishistory',
            name='red_flags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='analysishistory',
            name='sources_checked',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='analysishistory',
            name='verdict_label',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
